backend:
  name: github
  repo: gillespied/govuk-jekyll-template
  branch: add-decap-cms
  base_url: https://gillespied.github.io/govuk-jekyll-template
  auth_endpoint: oauth/authorize
  auth_type: pkce

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "people"
    label: "People"
    folder: "_people"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "widget"}
      - {label: "Image", name: "image", widget: "image"}