backend:
  name: test-repo

media_folder: "assets/uploads" # Folder where user uploaded files should go
public_folder: "/assets/uploads" # Folder that gets served up to the user

collections:
  - name: "people"
    label: "People"
    folder: "_people"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "text"}
      - {label: "Images", name: "images", widget: "image"}
